select name as "Media ID:Link/Media:100",
media_type as `Media Type`,
media_sub_type as `Sub Type`,
media_owner as "Media Owner:Data:120",
external_id as `External ID::100`,
COALESCE(NULLIF(film_title,''), tape_title) as `Title`,
film_element as `Film Element::110`,
film_sound as `Film Sound::100`,
film_colour as `Film Colour::100`,
film_year as `Film Year::95`,
film_length as `Film Length (ft)::125`,
is_checkerboard as `Is Checkerboard:Check:130`,
tape_standard as `Tape Standard::120`,
tape_manufacturer as `Tape Manufacturer::145`,
tape_run_time_mins as `Tape Runtime (mins)::160`,
drive_brand as `Drive Brand::110`,
drive_capacity as `Drive Capacity::120`,
drive_format as `Drive Formatting::130`,
has_datacable as `Has Data Cable:Check:125`,
has_psu as `Has PSU:Check:80`,
has_box as `Has Box:Check:80`,
notes as 'Notes::100'
from `tabMedia`
order by modified desc