select name as "ID:Link/Media:150",
media_type as Type,
media_sub_type as `Sub Type`,
media_owner as Owner,
external_id as `Ext ID`,
COALESCE(NULLIF(film_title,''), tape_title) as `Title`,
film_element as `Film Element`,
film_sound as `Film Sound`,
film_colour as `Film Colour`,
film_era as `Film Era`,
film_approximate_length_feet as `Film Length`,
is_checkerboard as `Is Checkerboard:Check:30`,
tape_standard as `Tape Standard`,
tape_manufacturer as `Tape Manufacturer`,
tape_run_time_mins as `Tape Runtime`,
drive_brand as `Drive Brand`,
drive_capacity as `Drive Capacity`,
drive_format as `Drive Format`,
has_datacable as `Cable:Check:30`,
has_psu as `PSU:Check:30`,
has_box as `Box:Check:30`,
content_description as Content,
notes as Notes
from `tabMedia`
order by modified desc